[book]
title = "Moxy"
authors = ["Alex Acebo"]
language = "en"

[rust]
edition = "2024"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/aacebo/moxy"
git-repository-icon = "fab-github"
additional-css = ["theme/moxy.css", "theme/highlight.css"]
additional-js = ["theme/moxy.js"]
smart-punctuation = true
definition-lists = true
sidebar-header-nav = true

[output.html.playground]
editable = false
runnable = false
